@startmindmap
* leetcode
** 数论
*** 质数问题
**** 判断一个数x是否是质数
**** 预处理质数（筛质数)：判断[1,MX]范围内哪些是质数，哪些不是
**** 对x做质因子分解
*** 因子、公约数问题
**** x 有哪些因子
**** x,y 有哪些公因子 (2423)
**** 最大公约数(1979)
**** 最小公倍数(x * y / gcd(x,y))
**** 互质 (gcd(x,y) == 1)

*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap