@startmindmap
* leetcode
** 数学
*** 质数问题
**** 判断一个数x是否是质数
**** 预处理质数（筛质数)：判断[1,MX]范围内哪些是质数，哪些不是
**** 对x做质因子分解
*** 因子、公约数问题
**** x 有哪些因子
**** x,y 有哪些公因子 (2423)
**** 最大公约数(1979)
**** 最小公倍数(x * y / gcd(x,y))
**** 互质 (gcd(x,y) == 1)
*** 几何
**** 距离、欧式距离、曼哈顿距离、切比雪夫距离
**** 曼哈顿距离和切比雪夫距离变换 d(A,B) = max(|x1-y1 - (x2-y2)|,|x1+y1-(x2+y2)|)
**** 如何求二维平面最大的曼哈顿距离？
**** 凸包
*** 组合
*** 随机算法
*** 概率期望
*** 博弈
*** 快速幂+mod


** 数据结构
*** 链表/双链
**** 单链表/双链表
**** 快慢指针
**** 哨兵节点dummy
**** 链表排序、插入排序、归并排序

*** 前缀和
**** 一维前缀和
**** 二维前缀和

*** 并查集

*** 线段树、差分、树状数组
**** 前缀和
***** 一维
***** 二维
**** 差分
***** 区间同时加上或者减去一个数
***** 一维
***** 二维
**** 树状数组
***** tree 数组的index 从1 开始
***** lowbit i = i & (-i)
***** 单点加或者更新一个数，求前缀和和区间和
**** 线段树
***** 支持单点、区间、支持加、更新，求区间最值等问题





** 贪心算法

** 图论
*** 最短路
**** BFS无权图
**** 单源权值为正djkstra(nlog(E))
**** 单源权值可为负bellmanFord.(n-1)*O(E)
**** 多源floyd(n^3)

*** 拓扑排序,in 入度数组

*** 最小生成树:排序,贪心,UnionFind，Kruskal/Prim

*** 欧拉路径/欧拉回路 Hierholzer

*** 强连通分量/双连通分量 Tarjan

*** 二分图 （染色判定、最大匹配）

*** 网络流


left side

** 基础算法

*** 滑动窗口/双指针
**** 定长
**** 不定长
**** 多指针
*** 二分法
*** 排序
*** 单调栈
*** 位运算
**** AND 和 OR  性质
**** 二进制状态枚举 mask

** 搜索应用
*** BFS
**** 一维、二维网格、树、图
*** DFS
**** 一维、二维网格、树、图
**** 找多所有符合条件的路径
*** 启发式搜索

** 动态规划
*** 线性DP
**** 一维
**** 二维、网格
**** 入门
***** 爬楼梯
***** 打家劫舍
***** 最大子数组和
**** 序列DP

*** 背包
**** 0-1背包
**** 完全背包
**** 多重背包
**** 分组背包

*** 状态机 DP
*** 划分型 DP
**** 判定能否划分
**** 计算划分最优值
**** 约束划分个数
**** 不相交区间
*** 其他线性 DP
*** 区间 DP
*** 状态压缩 DP
*** 数位 DP
**** 用途:统计符合条件的整数的数量
****[#Red] 模板:dfs(i,state,is_limt,is_num)
**** 常见题
***** 600. 统计[0,n]中二进制不含连续1的整数的数量
***** 233. 统计[1,n]中所有整数1的数量
*** 数据结构优化 DP
*** 树形 DP
**** 定根DP，一次扫描
***** 树的直径
***** 树的最大路径和
**** 换更DP，两次扫描
***** 树中每个节点距离其它节点的距离和
*** 图 DP
*** 博弈 DP
*** 概率/期望 DP

***[#Red] dp方案数量

***[#Red] dp最大/最小/最长

@endmindmap